<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
'key' => 'group_6279z4451fd5c',
'title' => 'Hero',
'fields' => array(
array(
'key' => 'field_6279z58a76a3c',
'label' => 'Layout Settings',
'name' => 'layout_settings',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6279z59f76a3d',
		'label' => 'Height',
		'name' => 'height',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'normal' => 'Normal',
			'short' => 'Short',
			'full' => 'Full',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6279z5db76a3e',
		'label' => 'Display Advance Arrow',
		'name' => 'display_advance_arrow',
		'type' => 'checkbox',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'yes' => 'Yes',
		),
		'allow_custom' => 0,
		'default_value' => array(
		),
		'layout' => 'vertical',
		'toggle' => 0,
		'return_format' => 'value',
		'save_custom' => 0,
	),
),
),
array(
'key' => 'field_6279z57609d34',
'label' => 'Content Settings',
'name' => 'content_settings',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6279z64d97a58',
		'label' => 'Title',
		'name' => 'title',
		'type' => 'textarea',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'maxlength' => '',
		'rows' => '',
		'new_lines' => '',
	),
	array(
		'key' => 'field_627994e4a72fd',
		'label' => 'Title Size',
		'name' => 'title_size',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'h1' => 'H1',
			'h2' => 'H2',
			'h3' => 'H3',
			'h4' => 'H4',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => 'h1',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6279z9ff8e607',
		'label' => 'Title Color',
		'name' => 'title_color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '#ffffff',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_6279z68097a5a',
		'label' => 'Title Alignment',
		'name' => 'title_alignment',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'left' => 'Left',
			'center' => 'Center',
			'right' => 'Right',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_627bb97983d2a',
		'label' => 'Secondary Title',
		'name' => 'secondary_title',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_627bb98383d2b',
		'label' => 'Secondary Title Color',
		'name' => 'secondary_title_color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_627bb9cb83d2c',
		'label' => 'Secondary Title Placement',
		'name' => 'secondary_title_placement',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'before' => 'Before Title',
			'after' => 'After Title',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6279z65597a59',
		'label' => 'Copy',
		'name' => 'copy',
		'type' => 'textarea',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'maxlength' => '',
		'rows' => '',
		'new_lines' => '',
	),
	array(
		'key' => 'field_6279za088e608',
		'label' => 'Copy Color',
		'name' => 'copy_color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '#ffffff',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_6279z69b97a5b',
		'label' => 'Copy Aligment',
		'name' => 'copy_aligment',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'left' => 'Left',
			'center' => 'Center',
			'right' => 'Right',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6279z6dc97a5d',
		'label' => 'Buttons',
		'name' => 'buttons',
		'type' => 'repeater',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'collapsed' => '',
		'min' => 0,
		'max' => 0,
		'layout' => 'table',
		'button_label' => '',
		'sub_fields' => array(
			array(
				'key' => 'field_6279z6e897a5e',
				'label' => 'Button',
				'name' => 'button',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
		),
	),
	array(
		'key' => 'field_627bce357ffac',
		'label' => 'Buttons Alignment',
		'name' => 'buttons_alignment',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'flex-start' => 'Left',
			'center' => 'Center',
			'flex-end' => 'Right',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6279z6b297a5c',
		'label' => 'Content Width',
		'name' => 'content_width',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			100 => '100%',
			75 => '75%',
			50 => '50%',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6279zab5ff44a',
		'label' => 'Content Vertical Alignment',
		'name' => 'content_vertical_alignment',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'center' => 'Center',
			'flex-start' => 'Top',
			'flex-end' => 'Bottom',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6279zad9ff44b',
		'label' => 'Content Horizontal Alignment',
		'name' => 'content_horizontal_alignment',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'center' => 'Center',
			'left' => 'Left',
			'right' => 'Right',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
),
),
array(
'key' => 'field_6279z44b82ea0',
'label' => 'Background Settings',
'name' => 'background_settings',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_6279z46782ea1',
		'label' => 'Image',
		'name' => 'image',
		'type' => 'image',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'return_format' => 'array',
		'preview_size' => 'medium',
		'library' => 'all',
		'min_width' => '',
		'min_height' => '',
		'min_size' => '',
		'max_width' => '',
		'max_height' => '',
		'max_size' => '',
		'mime_types' => '',
	),
	array(
		'key' => 'field_6279z48d82ea2',
		'label' => 'Image Sizing',
		'name' => 'image_sizing',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'cover' => 'Cover',
			'contain' => 'Contain',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => 'cover',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6279z4b682ea3',
		'label' => 'Image Vertical Alignment',
		'name' => 'image_vertical_alignment',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'center' => 'Center',
			'top' => 'Top',
			'bottom' => 'Bottom',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6279z4d782ea4',
		'label' => 'Image Horizontal Alignment',
		'name' => 'image_horizontal_alignment',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'center' => 'Center',
			'left' => 'Left',
			'right' => 'Right',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6279z62a3fbc7',
		'label' => 'Video (mp4)',
		'name' => 'video_mp4',
		'type' => 'file',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'return_format' => 'array',
		'library' => 'all',
		'min_size' => '',
		'max_size' => '',
		'mime_types' => '',
	),
	array(
		'key' => 'field_6279z55482ea7',
		'label' => 'Background Color',
		'name' => 'background_color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_6279z4f282ea5',
		'label' => 'Overlay Color',
		'name' => 'overlay_color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '#000000',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_6279z50a82ea6',
		'label' => 'Overlay Opacity',
		'name' => 'overlay_opacity',
		'type' => 'range',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'min' => '',
		'max' => '',
		'step' => '',
		'prepend' => '',
		'append' => '',
	),
),
),
),
'location' => array(
array(
array(
	'param' => 'block',
	'operator' => '==',
	'value' => 'acf/hero',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
));

endif;
