<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
  'key' => 'group_6347354a3908a',
  'title' => 'Timeline',
  'fields' => array(
    array(
      'key' => 'field_6347357baf030',
      'label' => 'Timeline Settings',
      'name' => 'timeline_settings',
      'type' => 'group',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layout' => 'block',
      'sub_fields' => array(
        array(
          'key' => 'field_6347358faf031',
          'label' => 'Order',
          'name' => 'order',
          'type' => 'radio',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array(
            'desc' => 'Descending',
            'asc' => 'Ascending',
          ),
          'default_value' => 'desc',
          'return_format' => 'value',
          'allow_null' => 0,
          'other_choice' => 0,
          'save_other_choice' => 0,
          'layout' => 'vertical',
        ),
      ),
    ),
    array(
      'key' => 'field_634735cbaf032',
      'label' => 'Timeline Items',
      'name' => 'timeline_items',
      'type' => 'group',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'layout' => 'block',
      'sub_fields' => array(
        array(
          'key' => 'field_634735e7af033',
          'label' => 'Heading Color',
          'name' => 'heading_color',
          'type' => 'color_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'enable_opacity' => 0,
          'return_format' => 'string',
        ),
        array(
          'key' => 'field_634735f9af034',
          'label' => 'Copy Color',
          'name' => 'copy_color',
          'type' => 'color_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'enable_opacity' => 0,
          'return_format' => 'string',
        ),
        array(
          'key' => 'field_63473615af035',
          'label' => 'Timeline Item',
          'name' => 'timeline_item',
          'type' => 'repeater',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'layout' => 'row',
          'pagination' => 0,
          'min' => 0,
          'max' => 0,
          'collapsed' => '',
          'button_label' => 'Add Row',
          'rows_per_page' => 20,
          'sub_fields' => array(
            array(
              'key' => 'field_634737df61776',
              'label' => 'Date',
              'name' => 'date',
              'type' => 'date_picker',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'display_format' => 'F j, Y',
              'return_format' => 'Ymd',
              'first_day' => 1,
              'parent_repeater' => 'field_63473615af035',
            ),
            array(
              'key' => 'field_63473623af036',
              'label' => 'Heading',
              'name' => 'heading',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'maxlength' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'parent_repeater' => 'field_63473615af035',
            ),
            array(
              'key' => 'field_63473629af037',
              'label' => 'Copy',
              'name' => 'copy',
              'type' => 'textarea',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'maxlength' => '',
              'rows' => '',
              'placeholder' => '',
              'new_lines' => '',
              'parent_repeater' => 'field_63473615af035',
            ),
            array(
              'key' => 'field_63473629af038',
              'label' => 'Selected Leadership Transactions',
              'name' => 'selected_leadership_transactions',
              'type' => 'post_object',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'post_type' => array(
                0 => 'case_studies',
              ),
              'taxonomy' => '',
              'allow_null' => 0,
              'multiple' => 1,
              'return_format' => 'id',
              'ui' => 1,
            ),
          ),
        ),
      ),
    ),
  ),
  'location' => array(
    array(
      array(
        'param' => 'block',
        'operator' => '==',
        'value' => 'acf/timeline',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => true,
  'description' => '',
  'show_in_rest' => 0,
));

endif;    