<?php 

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_64ca8dcacdd18',
	'title' => 'Reveal Heading',
	'fields' => array(
		array(
			'key' => 'field_64ca8dcb6d427',
			'label' => 'Heading',
			'name' => 'heading',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_64ca8dda6d428',
			'label' => 'Size',
			'name' => 'size',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'choices' => array(
				'h1' => 'H1',
				'h2' => 'H2',
				'h3' => 'H3',
				'h4' => 'H4',
				'h5' => 'H5',
				'h6' => 'H6',
			),
			'default_value' => 'h2',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_64cbead6714d2',
			'label' => 'Type of animation',
			'name' => 'type',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'choices' => array(
				'color-change' => 'Color Change',
				'fade-in-up' => 'Fade In Up',
			),
			'default_value' => 'color-change',
			'return_format' => 'value',
			'allow_null' => 0,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_64ca8e146d429',
			'label' => 'Background Color',
			'name' => 'background_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64cbead6714d2',
						'operator' => '==contains',
						'value' => 'color-change',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'default_value' => '#ffffff',
			'enable_opacity' => 0,
			'return_format' => 'string',
			'display' => 'default',
			'button_label' => 'Select Color',
			'color_picker' => 1,
			'absolute' => 0,
			'input' => 1,
			'allow_null' => 0,
			'theme_colors' => 1,
			'colors' => array(
			),
		),
		array(
			'key' => 'field_64ca8e476d42a',
			'label' => 'Foreground Color',
			'name' => 'foreground_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_64cbead6714d2',
						'operator' => '==contains',
						'value' => 'color-change',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'default_value' => '#000000',
			'enable_opacity' => 0,
			'return_format' => 'string',
			'display' => 'default',
			'button_label' => 'Select Color',
			'color_picker' => 1,
			'absolute' => 0,
			'input' => 1,
			'allow_null' => 0,
			'theme_colors' => 1,
			'colors' => array(
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/reveal-heading',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => array(
		0 => 'json',
	),
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
) );
} );

