<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
'key' => 'group_6281627e3b4c6',
'title' => 'Callout Box',
'fields' => array(
array(
'key' => 'field_62816436ed85c',
'label' => 'Layout Settings',
'name' => 'layout_settings',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_62816483ed85e',
		'label' => 'Background Color',
		'name' => 'background_color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_6281691b3e244',
		'label' => 'Padding',
		'name' => 'padding',
		'type' => 'range',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => 45,
		'min' => 30,
		'max' => 120,
		'step' => 15,
		'prepend' => '',
		'append' => 'px',
	),
),
),
array(
'key' => 'field_628162b810950',
'label' => 'Image Settings',
'name' => 'image_settings',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_628162ea10951',
		'label' => 'Image',
		'name' => 'image',
		'type' => 'image',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'return_format' => 'array',
		'preview_size' => 'medium',
		'library' => 'all',
		'min_width' => '',
		'min_height' => '',
		'min_size' => '',
		'max_width' => '',
		'max_height' => '',
		'max_size' => '',
		'mime_types' => '',
	),
	array(
		'key' => 'field_628162fa10952',
		'label' => 'Image Sizing',
		'name' => 'image_sizing',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'cover' => 'Cover',
			'contain' => 'Contain',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6281631310953',
		'label' => 'Image Placement',
		'name' => 'image_placement',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'left' => 'Left',
			'right' => 'Right',
			'top' => 'Top',
			'bottom' => 'Bottom',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6281633c10954',
		'label' => 'Image Width',
		'name' => 'image_width',
		'type' => 'range',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'min' => 20,
		'max' => 100,
		'step' => 5,
		'prepend' => '',
		'append' => '%',
	),
	array(
		'key' => 'field_6281639b10955',
		'label' => 'Image Offset Top',
		'name' => 'image_offset_top',
		'type' => 'range',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => 0,
		'min' => -120,
		'max' => 120,
		'step' => 10,
		'prepend' => '',
		'append' => 'px',
	),
	array(
		'key' => 'field_628163fe10956',
		'label' => 'Image Overlap',
		'name' => 'image_overlap',
		'type' => 'range',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => 0,
		'min' => '',
		'max' => 120,
		'step' => 10,
		'prepend' => '',
		'append' => 'px',
	),
	array(
		'key' => 'field_6281631310950',
		'label' => 'Image X Axis Alignment',
		'name' => 'image_x_alignment',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'center' => 'Center',
			'left' => 'Left',
			'right' => 'Right',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => 'center',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6281631310951',
		'label' => 'Image Y Axis Alignment',
		'name' => 'image_y_alignment',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'center' => 'Center',
			'top' => 'Top',
			'bottom' => 'Bottom',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => 'center',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_6281679b5b5c7',
		'label' => 'Image Overlay',
		'name' => 'image_overlay',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'under' => 'Image Underneath Content',
			'over' => 'Image Over Content',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
),
),
array(
'key' => 'field_62816471ed85d',
'label' => 'Content Settings',
'name' => 'content_settings',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
	'width' => '',
	'class' => '',
	'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
	array(
		'key' => 'field_62816491ed85f',
		'label' => 'TItle',
		'name' => 'title',
		'type' => 'textarea',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'maxlength' => '',
		'rows' => '',
		'new_lines' => '',
	),
	array(
		'key' => 'field_628164baed860',
		'label' => 'Title Color',
		'name' => 'title_color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_628163131095z',
		'label' => 'Title Logo Mark',
		'name' => 'title_logo_mark',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'' => 'None',
			'logo-mark-blue-700' => 'Blue 700',
			'logo-mark-white' => 'White',
			'logo-mark-beige-400' => 'Beige 400',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_628164e1ed863',
		'label' => 'Secondary Title',
		'name' => 'secondary_title',
		'type' => 'text',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'prepend' => '',
		'append' => '',
		'maxlength' => '',
	),
	array(
		'key' => 'field_628164e8ed864',
		'label' => 'Secondary Title Color',
		'name' => 'secondary_title_color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_628164f5ed865',
		'label' => 'Secondary Title Placement',
		'name' => 'secondary_title_placement',
		'type' => 'radio',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'choices' => array(
			'before' => 'Before Title',
			'after' => 'After TItle',
		),
		'allow_null' => 0,
		'other_choice' => 0,
		'default_value' => '',
		'layout' => 'vertical',
		'return_format' => 'value',
		'save_other_choice' => 0,
	),
	array(
		'key' => 'field_628164cfed861',
		'label' => 'Copy',
		'name' => 'copy',
		'type' => 'textarea',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'placeholder' => '',
		'maxlength' => '',
		'rows' => '',
		'new_lines' => '',
	),
	array(
		'key' => 'field_628164d6ed862',
		'label' => 'Copy Color',
		'name' => 'copy_color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
	array(
		'key' => 'field_6281650fed866',
		'label' => 'Buttons',
		'name' => 'buttons',
		'type' => 'repeater',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'collapsed' => '',
		'min' => 0,
		'max' => 0,
		'layout' => 'table',
		'button_label' => '',
		'sub_fields' => array(
			array(
				'key' => 'field_62816518ed867',
				'label' => 'Button',
				'name' => 'button',
				'type' => 'link',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
			),
		),
	),
	array(
		'key' => 'field_62816483ed85z',
		'label' => 'Background Color',
		'name' => 'background_color',
		'type' => 'color_picker',
		'instructions' => '',
		'required' => 0,
		'conditional_logic' => 0,
		'wrapper' => array(
			'width' => '',
			'class' => '',
			'id' => '',
		),
		'default_value' => '',
		'enable_opacity' => 0,
		'return_format' => 'string',
	),
),
),
),
'location' => array(
array(
array(
	'param' => 'block',
	'operator' => '==',
	'value' => 'acf/callout-box',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
));

endif;
