<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6d0a8ba5980e7',
	'title' => 'Image Grid',
	'fields' => array(
		array(
			'key' => 'field_6e56871afe23r',
			'label' => 'Layout Options',
			'name' => 'layout_options',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'0_0_0'    => 'Automatic',
				'33_33_33' => '33% 33% 33%',
				'50_25_25' => '50% 25% 25%',
				'25_50_25' => '25% 50% 25%',
				'25_25_50' => '25% 25% 50%',
				'66_33'    => '66% 33%',
				'33_66'    => '33% 66%',
				'50_50'    => '50% 50%',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6e56871afe239',
			'label' => 'Image Grid Items',
			'name' => 'icon_grid_items',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
	    			'key' => 'field_6d0a8c3c3ba3f',
	    			'label' => 'Background',
	    			'name' => 'background',
	    			'type' => 'image',
	    			'instructions' => '',
	    			'required' => 0,
	    			'conditional_logic' => 0,
	    			'wrapper' => array(
	    				'width' => '',
	    				'class' => '',
	    				'id' => '',
	    			),
	    			'return_format' => 'array',
	    			'preview_size' => 'medium',
	    			'library' => 'all',
	    			'min_width' => '',
	    			'min_height' => '',
	    			'min_size' => '',
	    			'max_width' => '',
	    			'max_height' => '',
	    			'max_size' => '',
	    			'mime_types' => '',
	    		),
				array(
					'key' => 'field_6d0a8bad3ba39',
					'label' => 'Link',
					'name' => 'link',
					'type' => 'link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
				),
				array(
					'key' => 'field_6d0a8bad3ba3d',
					'label' => 'Copy',
					'name' => 'copy',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/image-grid',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;
